# this configuration file has all empty components set up.
# use 'esphome compile test_empty_components.yaml' to build.

packages:
  device: !include device.yaml  # include our test device setup

i2c:
  sda: 22
  scl: 23
  scan: True
  id: bus_a
  frequency: 50kHz


bq21088:
  i2c_id: bus_a
  id: bq_test

switch:
  - platform: bq21088
    bq21088_id: bq_test
    charge_disable:
      name: Laden deaktivieren

number:
  - platform: bq21088
    bq21088_id: bq_test
    vbat:
      name: Battery Endladespannung
    icgh:
      name: Battery Ladestrom

sensor:
  - platform: bq21088
    bq21088_id: bq_test
    charge_status:
      name: Ladezustand
